#!/bin/sh

set -e

PREREQ=""

prereqs()
{
        echo "${PREREQ}"
}

case "${1}" in
        prereqs)
                prereqs
                exit 0
                ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /lib/libresolv* /lib
copy_exec /usr/lib/libpci.so.* /lib
copy_exec /usr/bin/lspci /bin

