#!/bin/sh
# Copying local grub2 configuration files

case "$LB_BOOTLOADER" in
grub2|burg)
	;;
*)
	exit 0
	;;
esac

if [ -f config/binary_grub/grub.cfg ]
then
	mkdir -p binary/boot/grub
        cp config/binary_grub/grub*.cfg binary/boot/grub/
        cp config/binary_grub/loopback.cfg binary/boot/grub/
fi

. config/chroot

if echo "$LB_PACKAGE_LISTS" | grep -qw gfxdetect; then
	# keep gfxdetect entries in grub.cfg (for gfxdetect-builds)
	echo "grub2-configs: keeping gfxdetect entries"
else
	# remove gfxdetect entries from grub.cfg (for non-gfxdetect-builds)
	sed -i '/gfxdetect/,/^}/{d}' binary/boot/grub/grub.cfg
fi

