#!/bin/bash
# generate binary/boot.isohybrid for isohybrid-acritox

[ "${LB_BINARY_IMAGES}" = "iso-hybrid" ] || exit 0

case "$LB_BOOTLOADER" in
grub2|burg)
	;;
*)
	exit 0
	;;
esac

chroot chroot grub-mkimage -d /usr/lib/grub/i386-pc -o "/boot.isohybrid" -O i386-pc biosdisk iso9660
for i in $(seq 64); do echo -n "ACRITOX!"; done > binary/boot.isohybrid
cat chroot/boot.isohybrid >> binary/boot.isohybrid
rm -f chroot/boot.isohybrid

