#!/bin/bash

# Update kanotix-version timestamp
perl -pi -e "s|[0-9]+-[0-9]+:[0-9]+|$(date +%Y%m%d-%H:%M)|" > config/chroot_local-includes/etc/kanotix-version

lh build noauto ${@} 2>&1 | tee binary.log
