#!/bin/bash

MIRROR_CHROOT=http://ftp.de.debian.org/debian
MIRROR_CHROOT_SECURITY=http://security.debian.org/
MIRROR_BINARY=http://ftp.de.debian.org/debian
MIRROR_BINARY_SECURITY=http://security.debian.org/
MIRROR_BOOTSTRAP="$MIRROR_CHROOT"

. auto/kanotix

lb config noauto \
	--iso-volume KANOTIX \
	--iso-preparer kanotix.com \
	--iso-publisher kanotix.com \
	--chroot-filesystem squashfs \
	--debian-installer false \
	--apt aptitude \
	--apt-recommends false \
	--bootappend-live 'splash utc=no timezone=Europe/Berlin locales=de keyboard-layouts=de keyboard-variant=nodeadkeys' \
	--distribution squeeze \
        --archive-areas "main contrib non-free" \
	--repositories "live.debian.net acritox excalibur hellfire" \
	--security true \
	--checksums md5 \
	--bootloader syslinux \
	--syslinux-timeout 5 \
	--syslinux-menu true \
	--syslinux-splash config/binary_syslinux/splash.png \
	--memtest memtest86+ \
	--mirror-bootstrap ${MIRROR_BOOTSTRAP} \
	--mirror-chroot ${MIRROR_CHROOT} \
	--mirror-chroot-security ${MIRROR_CHROOT_SECURITY} \
	--mirror-binary ${MIRROR_BINARY} \
	--mirror-binary-security ${MIRROR_BINARY_SECURITY} \
	--binary-indices true \
	--packages-lists "standard-x11" \
	${@}

# hostname and username are configured in config/chroot_local-includes/etc/live/config.conf
#lb config noauto \
#	--hostname Kanotix \
#	--username kanotix \

. config/bootstrap

# architecture depending stuff (e.g. kernel)
case $LB_ARCHITECTURE in
"amd64")
  lb config noauto \
        --linux-flavours amd64 \
        --linux-packages "linux-image-2.6 linux-headers-2.6"
	;;
"i386")
  lb config noauto \
        --linux-flavours 686-bigmem \
        --linux-packages "linux-image-2.6 linux-headers-2.6"
	;;
esac

# Fetch kanotix-scripts if necessary
mkdir -p config/chroot_local-includes/usr/local/bin
grep -oe '^[^ #]*' scripts.urls | wget -i- -N -q -P config/chroot_local-includes/usr/local/bin
chmod 755 config/chroot_local-includes/usr/local/bin/*.sh

exit 1

