#!/bin/bash

MIRROR_CHROOT=http://ftp.de.debian.org/debian
MIRROR_CHROOT_SECURITY=http://security.debian.org/
MIRROR_BINARY=http://ftp.de.debian.org/debian
MIRROR_BINARY_SECURITY=http://security.debian.org/
MIRROR_BOOTSTRAP="$MIRROR_CHROOT"

. auto/kanotix

# preset kanotix defaults
export LB_PACKAGES_LISTS="kanotix-master"
export LB_DISTRIBUTION="wheezy"
export LB_BOOTLOADER="grub2"
export LB_SYSLINUX_MENU_LIVE_ENTRY="Kanotix"
export LB_LINUX_PACKAGES="linux-image linux-headers"

lb config noauto \
	--iso-volume KANOTIX \
	--iso-preparer kanotix.com \
	--iso-publisher kanotix.com \
	--binary-images iso-hybrid \
	--chroot-filesystem squashfs \
	--debian-installer false \
	--apt apt \
	--apt-recommends false \
	--bootappend-live 'utc=no timezone=Europe/Berlin locales=de keyboard-layouts=de keyboard-variant=nodeadkeys splash' \
        --archive-areas "main contrib non-free" \
	--repositories "live.debian.net lo" \
	--security true \
	--checksums md5 \
	--syslinux-timeout 5 \
	--syslinux-menu true \
	--syslinux-splash config/binary_syslinux/splash.png \
	--memtest memtest86+ \
	--mirror-bootstrap ${MIRROR_BOOTSTRAP} \
	--mirror-chroot ${MIRROR_CHROOT} \
	--mirror-chroot-security ${MIRROR_CHROOT_SECURITY} \
	--mirror-binary ${MIRROR_BINARY} \
	--mirror-binary-security ${MIRROR_BINARY_SECURITY} \
	--binary-indices true \
	--firmware-binary false \
	--firmware-chroot false \
	"${@}" || exit $?

. config/binary
. config/bootstrap
. config/chroot

# architecture and distribution depending stuff (e.g. kernel)
case "$LB_DISTRIBUTION" in
wheezy)
	LB_REPOSITORIES+=" dragonfire fds-team-wheezy fds-team-source dragonfire-acritox"
	case $LB_ARCHITECTURE in
	amd64) LB_LINUX_PACKAGES="linux-image linux-headers"; LB_LINUX_FLAVOURS="amd64";;
	i386)  LB_LINUX_PACKAGES="linux-image linux-headers"; LB_LINUX_FLAVOURS="686-pae";;
	esac
	;;
jessie)
    LB_REPOSITORIES+=" dragonfire spitfire fds-team-debian fds-team-source spitfire-acritox"
	case $LB_ARCHITECTURE in
	amd64) LB_LINUX_PACKAGES="linux-image linux-headers"; LB_LINUX_FLAVOURS="amd64";;
	i386)  LB_LINUX_PACKAGES="linux-image linux-headers"; LB_LINUX_FLAVOURS="686-pae";;
	esac
	;;
*)
    LB_REPOSITORIES+=" dragonfire spitfire fds-team-debian fds-team-source spitfire-acritox"
	case $LB_ARCHITECTURE in
	amd64) LB_LINUX_PACKAGES="linux-image linux-headers"; LB_LINUX_FLAVOURS="amd64";;
	i386)  LB_LINUX_PACKAGES="linux-image linux-headers"; LB_LINUX_FLAVOURS="686-pae";;
	esac
	;;
esac

[ "$LB_BOOTLOADER" = "burg" ] && LB_REPOSITORIES+=" burg"
grep -wq acritox <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" acritox dragonfire-acritox"
grep -wq hellfire <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" hellfire"
grep -wq trinity <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" trinity"
grep -wq -e virtualbox -e vbox <<<"$LB_PACKAGES $LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" vbox"
grep -wq -e opera <<<"$LB_PACKAGES $LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" opera"
grep -wq google-chrome <<<"$LB_PACKAGES $LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" google-chrome"
grep -wq -e hangouts -e google-talkplugin <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" google-talkplugin"
grep -wq google-earth <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" google-earth"
grep -wq mesa <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" mesa"
grep -wq msa9 <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" mesa-9"
grep -wq ms11 <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" mesa-11"
grep -wq msos <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" mesa-steamos"
grep -wq nvidia <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" nvidia"
grep -wq fglrx <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" fglrx"
if grep -wq steam <<<"$LB_PACKAGES_LISTS"; then
    if [ "$LB_DISTRIBUTION" = "wheezy" ]; then
        LB_REPOSITORIES+=" steam steam-wheezy"
    else
        LB_REPOSITORIES+=" steam"
    fi
fi
if grep -wq wine-staging <<<"$LB_PACKAGES $LB_PACKAGES_LISTS"; then
    if [ "$LB_DISTRIBUTION" = "wheezy" ]; then
        LB_REPOSITORIES+=" fds-team-wheezy fds-team-source"
    else
        LB_REPOSITORIES+=" fds-team-debian fds-team-source"
    fi
fi
grep -wq iceweasel <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" iceweasel"
grep -wq firefox <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" firefox"
grep -wq silverlight <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" silverlight"
grep -wq spotify <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" spotify"
grep -wq dropbox <<<"$LB_PACKAGES_LISTS" && LB_REPOSITORIES+=" dropbox"
lb config noauto --linux-packages "$LB_LINUX_PACKAGES" --linux-flavours "$LB_LINUX_FLAVOURS" --repositories "$LB_REPOSITORIES"

# Fetch kanotix-scripts if necessary
mkdir -p config/chroot_local-includes/usr/local/bin
grep -oe '^[^ #]*' scripts.urls | wget -i- -N -q -P config/chroot_local-includes/usr/local/bin
chmod 755 config/chroot_local-includes/usr/local/bin/*sh || :

