#!/bin/bash
if grep -q "Apple.*Keyboard" /proc/bus/input/devices; then
    # set keyboard model to macbook79
    echo "keyboard-configuration keyboard-configuration/modelcode select macbook79" | debconf-set-selections 
    sed -i -e "s|^XKBMODEL=.*$|XKBMODEL=\"macbook79\"|" /etc/default/keyboard
    
    # reverse scroll wheel
    echo "[Mouse]" > /etc/skel/.kde/share/config/kcminputrc
    echo "ReverseScrollPolarity=true" >> /etc/skel/.kde/share/config/kcminputrc

    # disable tap = click because Apple Trackpads have an own click button
    sed -i 's/^\(.*"f1_tap_action":\) [01]\(.*\)$/\1 0\2/' /etc/skel/.config/synaptiks/touchpad-config.json
fi
