#!/bin/sh

Nocompiz ()
{
	# Checking if configured
	if [ -e /var/lib/live/config/nocompiz ]
	then
		return
	fi
	echo -n " nocompiz"
	Configure_nocompiz
}

Configure_nocompiz ()
{
	# Boot parameters can be acted up either this way...
	if ! grep -qs "nocompiz" /proc/cmdline
	then
		return
	fi
	rm -f /home/${LIVE_USERNAME}/.config/autostart/compiz_start.desktop
	# Creating state file
	touch /var/lib/live/config/nocompiz
}

Nocompiz
