#!/bin/sh

Composit ()
{
	# Checking if configured
	if [ -e /var/lib/live/config/composit ]
	then
		return
	fi
	echo -n " composit"
	Configure_composit
}
Configure_composit ()
{
	# Boot parameters can be acted up either this way...
	if grep -qs "compton" /proc/cmdline
	then
	    touch /home/${LIVE_USERNAME}/.compton
	    touch /home/${LIVE_USERNAME}/.nocompiz
	    chown 1000:1000 /home/${LIVE_USERNAME}/.compton
	    chown 1000:1000 /home/${LIVE_USERNAME}/.nocompiz
	fi
	if grep -qs "nocompiz" /proc/cmdline
	then
	    touch /home/${LIVE_USERNAME}/.nocompiz
	    if [ -e /home/${LIVE_USERNAME}/.config/kwinrc ]; then
		echo "[Compositing]" >>/home/${LIVE_USERNAME}/.config/kwinrc
		echo "Enabled=false" >>/home/${LIVE_USERNAME}/.config/kwinrc
	    fi
	fi
	if grep -qs "awesome" /proc/cmdline
	then
	    if [ -x /usr/bin/awesome ]; then
		touch /home/${LIVE_USERNAME}/.nocompiz
		touch /home/${LIVE_USERNAME}/.awesome-wmanager
		chown 1000:1000 /home/${LIVE_USERNAME}/.compton
		chown 1000:1000 /home/${LIVE_USERNAME}/.awesome-wmanager
		echo "[Desktop]" >/home/${LIVE_USERNAME}/.dmrc
		echo "Session=awesome" >>/home/${LIVE_USERNAME}/.dmrc
		chown 1000:1000 /home/${LIVE_USERNAME}/.dmrc
	    fi
	fi
	
	if grep -qs "xbmc" /proc/cmdline
	then
	    if [ -x /usr/bin/xbmc ]; then
		touch /home/${LIVE_USERNAME}/.nocompiz
		chown 1000:1000 /home/${LIVE_USERNAME}/.nocompiz
		echo "[Desktop]" >/home/${LIVE_USERNAME}/.dmrc
		echo "Session=XBMC" >>/home/${LIVE_USERNAME}/.dmrc
		chown 1000:1000 /home/${LIVE_USERNAME}/.dmrc
	    fi
	fi
	# Creating state file
	touch /var/lib/live/config/composit
}

Composit
