#!/bin/sh

[ ! -f /etc/gfxoverlay ] && exit 0

gfx="$(cat /etc/gfxoverlay)"
bit=32
[ "$(uname -m)" = "x86_64" ] && bit=64

mkdir -p /live/gfxoverlay /root/live/gfxoverlay
for overlay in /root/live/image/gfxoverlay.* /root/live/image/gfxoverlay/$gfx.*
do
    [ ! -e "$overlay" ] && continue
    mount -o loop "$overlay" /live/gfxoverlay
    for dir in /live/gfxoverlay/overlay$bit-$gfx /live/gfxoverlay/$gfx /live/gfxoverlay
    do
        if [ -d $dir/lib ]; then
            mount -o remount,add:1:$dir /root
            mount -n -o move /live/gfxoverlay /root/live/gfxoverlay
	    exit 0
	fi
    done
    umount /live/gfxoverlay
done
rmdir /live/gfxoverlay /root/live/gfxoverlay

