#!/bin/sh

img=/root/live/image/boot.efi.img

cd /root
if [ -e "$img" ]; then
    mkdir -p live/efipart
    mount -o loop "$img" live/efipart
    for file in live/efipart/*firmware*rpm
    do
        [ -e "$file" ] && /bin/chroot . rpm2cpio "/$file" | cpio -i
    done
    umount live/efipart
    rmdir live/efipart
fi

