#!/bin/sh
if [ -f /usr/share/applications/skype.desktop ]; then
 sed -i 's|\(Exec\)=.*|\1=XLIB_SKIP_ARGB_VISUALS=1 LD_PRELOAD=/usr/lib/libv4l/v4l1compat.so skype|' /usr/share/applications/skype.desktop || true
 [ -r /usr/lib32/libv4l/v4l1compat.so ] && sed -i 's|\(Exec\)=.*|\1=XLIB_SKIP_ARGB_VISUALS=1 LD_PRELOAD=/usr/lib32/libv4l/v4l1compat.so skype|' /usr/share/applications/skype.desktop || true
fi
