#!/bin/sh
for file in /root/config/*; do [ -r $file ] && . $file; done

echo "$LB_PACKAGE_LISTS" | grep -qw extra_cz || exit 0

if [ "$LB_DISTRIBUTION" = "buster" ]; then
    echo "D: language cz"

    if ! [ -x /usr/bin/lxde-logout ]; then
        apt install kde-l10n-cs
    fi

    if [ -x /var/lib/dpkg/info/firefox-esr.postinst ]; then
        apt install firefox-esr-l10n-cs
    fi

    if [ -x /var/lib/dpkg/info/thunderbird.postinst ]; then
        apt install thunderbird-l10n-cs
    fi

    # TODO lo version number

    if [ -x /var/lib/dpkg/info/libreoffice6.4-debian-menus.postinst ]; then
        apt install libobasis6.4-cs libobasis6.4-cs-help libreoffice6.4-cs
    fi

    if [ -e /etc/skel/.config/kxkbrc ]; then
        sed -i "s|,fr|,cz,fr|g" /etc/skel/.config/kxkbrc
    fi

    if [ -x /usr/bin/kanotix-lxde-keyboard ]; then
        sed -i "s|fr|cz|g" /usr/bin/kanotix-lxde-keyboard
    fi
fi
