#!/bin/sh

if [ -x /usr/sbin/lightdm ]; then
    # dirty hack kanotix wallpaper on login-screen
    echo "background=/usr/share/images/kanotix-starrise/kanotix-starrise.png" >>/etc/lightdm/lightdm-gtk-greeter.conf
    # enable display of users at login prompt
    sed -i 's/^greeter-hide-users=true/greeter-hide-users=false/' /etc/lightdm/lightdm.conf
    # script is called by lightdm
    if [ -x /usr/sbin/kanotix-lightdm-display-setup-script ]; then
	sed -i 's/^#display-setup-script=/display-setup-script=\/usr\/sbin\/kanotix-lightdm-display-setup-script/' /etc/lightdm/lightdm.conf
    fi
    # old kanotix icon in login
    sed -i 's/computer/kanotix/' /usr/share/lightdm-gtk-greeter/greeter.ui
    # Industrial conflicts
    sed -i s/Industrial/Clearlooks-Phenix/ /etc/skel/.gtkrc-2.0

    # on lxde i386 delete packages to reduce image-size
    if ! [ -d /lib/x86_64-linux-gnu ]; then
    apt-get purge --yes aptitude aptitude-common
    apt-get purge --yes vim vim-common vim-runtime
    fi
fi
