#!/bin/sh

if [ -x /usr/sbin/lightdm ]; then
    # dirty hack kanotix wallpaper on login-screen
    echo "background=/usr/share/images/kanotix-starrise/kanotix-starrise.png" >>/etc/lightdm/lightdm-gtk-greeter.conf
    # enable display of users at login prompt
    sed -i 's/^greeter-hide-users=true/greeter-hide-users=false/' /etc/lightdm/lightdm.conf
    # script is called by lightdm
    if [ -x /usr/sbin/kanotix-lightdm-display-setup-script ]; then
	sed -i 's/^#display-setup-script=/display-setup-script=\/usr\/sbin\/kanotix-lightdm-display-setup-script/' /etc/lightdm/lightdm.conf
    fi
    # old kanotix icon in login
    sed -i 's/computer/kanotix/' /usr/share/lightdm-gtk-greeter/greeter.ui
    # Industrial conflicts
    sed -i s/Industrial/Clearlooks-Phenix/ /etc/skel/.gtkrc-2.0

    # on lxde i386 delete packages to reduce image-size
    if ! [ -d /lib/x86_64-linux-gnu ]; then
    apt-get purge --yes aptitude aptitude-common
    apt-get purge --yes vim vim-common vim-runtime
    rm -rf /usr/lib/python3/dist-packages/devscripts
    apt-get purge --yes devscripts python3 python3-minimal python3.2 python3.2-minimal
    apt-get install --yes devscripts=2.12.6
    fi

    # tmp skel
    mkdir -p /etc/skel/Desktop/KANOTIX
    mkdir -p /etc/skel/.mplayer
    touch /etc/skel/.mplayer/input.conf
cat <<"EOF" >/etc/skel/.mplayer/config
[default]
# Write your default config options here!

#ao pulse
#ao alsa
#af=volnorm
#cache=4096
#aspect=16:9
EOF

fi
