#!/bin/sh
for file in /root/config/*; do [ -r $file ] && . $file; done

if [ "$LB_DISTRIBUTION" = "buster" ]; then

# enable tapping

mkdir -p /etc/X11/xorg.conf.d

cat <<"EOF" >/etc/X11/xorg.conf.d/40-libinput.conf
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
        #Option "DisableWhileTyping" "1"
EndSection
EOF

# set gtk2 theme
    sed -i s/Industrial/Clearlooks-Phenix/ /etc/skel/.gtkrc-2.0
    echo 'gtk-theme-name="Clearlooks-Phenix"' >>/etc/skel/.gtkrc-2.0
    ln -s .gtkrc-2.0 /etc/skel/.gtkrc-2.0-kde4


# powermanager fix new values for buster

mkdir -p /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml
cat <<"EOF" >/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-power-manager" version="1.0">
  <property name="xfce4-power-manager" type="empty">
    <property name="power-button-action" type="uint" value="3"/>
    <property name="show-tray-icon" type="bool" value="true"/>
    <property name="lid-action-on-battery" type="uint" value="1"/>
    <property name="critical-power-action" type="uint" value="1"/>
    <property name="spin-down-on-battery" type="bool" value="false"/>
    <property name="lock-screen-suspend-hibernate" type="bool" value="false"/>
    <property name="brightness-switch-restore-on-exit" type="int" value="1"/>
    <property name="brightness-switch" type="int" value="0"/>
  </property>
</channel>
EOF

# set compiz splash
    if [ -e /etc/skel/.config/compiz/compizconfig/Default.ini ]; then
        sed -i 's/splash_background_spitfire.png/splash_background_silverfire.png/' /etc/skel/.config/compiz/compizconfig/Default.ini
    fi

# hotfix lxde dead flag
    if [ -e /usr/share/lxpanel/images/xkb-flags/de.png ]; then
	cd /usr/share/lxpanel/images/xkb-flags
	ln -s de.png "de(nodeadkeys).png"
	cd -
    fi

fi
