#!/bin/sh
for file in /root/config/*; do [ -r $file ] && . $file; done

if [ "$LB_DISTRIBUTION" = "trixie" ]; then

# Remove 4 plasma icons added by taskmanager

if [ -f /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml ]; then
   sed -i 's/applications:systemsettings.desktop,applications:org.kde.discover.desktop,preferred:\/\/filemanager,preferred:\/\/browser//' /usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml
fi

# set flag as default in keyboard layout
if [ -f /usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/contents/config/main.xml ]; then
   sed -i 's/<default>0/<default>1/' /usr/share/plasma/plasmoids/org.kde.plasma.keyboardlayout/contents/config/main.xml
fi

# enable tapping

mkdir -p /etc/X11/xorg.conf.d

cat <<"EOF" >/etc/X11/xorg.conf.d/40-libinput.conf
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "Tapping" "on"
        #Option "DisableWhileTyping" "1"
EndSection
EOF

# set gtk3 theme
mkdir -p /etc/skel/.config/gtk-3.0
cat <<"EOF" >/etc/skel/.config/gtk-3.0/settings.ini
[Settings]
gtk-theme-name = Clearlooks-Phenix
EOF

# set gtk2 theme
mkdir -p /etc/skel
cat <<"EOF" >/etc/skel/.gtkrc-2.0
gtk-theme-name = "Clearlooks-Phenix"
EOF

# disable apt pager
echo 'Binary::apt::Pager "false";' > /etc/apt/apt.conf.d/98-nopager

# add scale factor for qt defaults to 100%
echo "QT_SCALE_FACTOR=1.0" >>/etc/environment

# fix for sddm layout
if [ -f /usr/share/sddm/scripts/Xsetup ]; then
   echo "setxkbmap" >> /usr/share/sddm/scripts/Xsetup
fi

# powermanager fix new values since buster

mkdir -p /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml
cat <<"EOF" >/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-power-manager" version="1.0">
  <property name="xfce4-power-manager" type="empty">
    <property name="power-button-action" type="uint" value="3"/>
    <property name="show-tray-icon" type="bool" value="true"/>
    <property name="lid-action-on-battery" type="uint" value="1"/>
    <property name="critical-power-action" type="uint" value="1"/>
    <property name="spin-down-on-battery" type="bool" value="false"/>
    <property name="lock-screen-suspend-hibernate" type="bool" value="false"/>
    <property name="brightness-switch-restore-on-exit" type="int" value="1"/>
    <property name="brightness-switch" type="int" value="0"/>
  </property>
</channel>
EOF

# set compiz splash
    if [ -e /etc/skel/.config/compiz/compizconfig/Default.ini ]; then
        sed -i 's/splash_background_spitfire.png/splash_background_towelfire.png/' /etc/skel/.config/compiz/compizconfig/Default.ini
    fi

# hotfix lxde dead flag
    if [ -e /usr/share/lxpanel/images/xkb-flags/de.png ]; then
	cd /usr/share/lxpanel/images/xkb-flags
	ln -s de.png "de(nodeadkeys).png"
	cd -
    fi

# annoying workaround for hpaio (disable prompt for root password in installed system)
    if [ -e /etc/sane.d/dll.d/hplip ]; then
        sed -i 's/^hpaio/#hpaio/' /etc/sane.d/dll.d/hplip
    fi

# replacement for hddtemp, load kernelmodul
mkdir -p /etc/modules-load.d
cat <<"EOF" >/etc/modules-load.d/drivetemp.conf
drivetemp
EOF

fi
