#!/bin/bash
for file in /root/config/*; do [ -r $file ] && . $file; done
echo "$LB_PACKAGE_LISTS" | grep -qw teamviewer || exit 0
TMP=$(mktemp -d /tmp/teamviewer.XXXXXX)
wget -NP $TMP http://download.teamviewer.com/download/teamviewer_i386.deb
dpkg -i $TMP/*.deb
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -f -y install
rm -rf $TMP
/etc/init.d/teamviewerd stop || :
killall teamviewerd || :
while sleep 1; do pidof teamviewerd >/dev/null || break; done
cat <<"EOF" >/opt/teamviewer/config/global.conf
TeamViewer Global Settings
# It is not recommended to edit this file manually


[int32] EulaAccepted = 1
[int32] EulaAcceptedRevision = 6
EOF
