#!/bin/sh
for w in wine-unstable wine-development; do
    if  [ -x /usr/bin/$w -a ! -x /usr/bin/wine ]; then
        printf '#!/bin/sh\n'$w' "$@"\n' > /usr/bin/wine
        chmod +x /usr/bin/wine
    fi
done

if [ -x /opt/wine-staging/bin/wine ]; then
    printf '#!/bin/sh\n/opt/wine-staging/bin/wine "$@"\n' > /usr/bin/wine
    chmod +x /usr/bin/wine
fi
